import LocalizedStrings from 'react-native-localization';
  
export let strings = new LocalizedStrings({
  "en-US":{
    Breed_Details:"Breed details",
    Breed_Name:"Breed name",
    Breed:"Breed",
    Save:"Save",
    Reset:"Reset",
    Breed_List:"Breed list",
    Search:"Search",
    Chicken_Treatment:"Chicken treatment",
    Chicken_Treatment_List:"Chicken treatment list",
    Purchased_Medicine_List:"Purchased medicine list",
    Purchased_Medicine:"Purchased medicine",
    Animal_Code:"Animal code",
    Medicine_Name:"Medicine name",
    Medicine_Type:"Medicine type",
    Medicine_Company:"Medicine company",
    Purchase_Date:"Purchase date",
    Reason:"Reason",
    Start_Date:"Start date",
    End_Date:"End date",
    Expiry_Date:"Expiry date",
    Batch_No:"Batch number",
    Quantity:"Quantity",
    Dosage:"Dosage",
    Remarks:"Remarks",
    Saved_successfully:"Saved successfully",
    Mandatory_fields:"Please enter all mandatory fields",
    Chicken_Treatment_Detail:"Chicken treatment detail",
    Chicken_Treatment_Entry_List:"Chicken treatment entry list",
    Supplied_By:"Supplied By",
    Chicken_Profile_Details:"Chicken profile details",
    Animal_Name:"Name",
    Animal_Symbol:"Symbol",
    Animal_Status:"Animal status",
    Cause_Of_Death:"Cause of death",
    Gender:"Gender",
    Sire_Code:"Sire code",
    Date_Of_Birth:"Date of birth",
    Breeder_Code:"Breeder code",
    Breeder_Formula:"Breeder formula",
    Talents:"Talents",
    Weight:"Weight",
    Fighting_Record:"Fighting record",
    Standard_Price:"Standard price",
    Chicken_Details:"Chicken details",
    Clear_Photo:"Clear photo",
    Select_Photo:"Select photo",
    Chicken_Profile_List:"Chicken profile list",
    Main_Dashboard:"Main dashboard",
    My_Farm_Dashboard:"My farm dashboard",
    Sales:"Sales",
    Expense:"Expense",
    Profit_Loss:"Profit & Loss",
    Stock:"Stock",
    Expense_Name:"Expense name",
    Expense_Code:"Expense code",
    Expense_Type:"Expense type",
    Vendor_Name:"Vendor name",
    Vendor_Address:"Vendor address",
    Amount:"Amount",
    Expense_Entry_Details:"Expense entry details",
    Expense_Entry_List:"Expense entry list",
    Expenses:"Expenses",
    Master_Expense_List:"Master expense list",
    Expense_Entry_List:"Expense entry list",
    Master_Expense_Details:"Master expense details",
    Farm_Profile:"Farm profile",
    Farm_Name:"Farm name",
    Farm_Address:"Farm address",
    Phone_Number:"Phone number",
    Mobile_Number:"Mobile number",
    Social_Page:"Social page",
    Website:"Website",
    About_Us:"About us",
    Line_ID:"Line ID",
    Add_Farm_Profile:"Add farm profile",
    Clear_Logo:"Clear logo",
    Select_Logo:"Select logo",
    OTP_Sent:"OTP successfully send to registered mobile number",
    Mobile_NumberNotExists:"Mobile number is not exists",
    Forgot_Password:"Forgot password",
    Continue:"Continue",
    Invalid_OTPNumber:"Invalid OTP Number..Please Enter Valid OTP Number.",
    Resend_OTP:"Resend OTP",
    New_Password:"New password",
    Confirm_Password:"Confirm password",
    Password_Mismatch:"Password mismatch",
    Successfully_ChangedPassword:"Successfully changed your password",
    Submit:"Submit",
    Password:"Password",
    Login:"Login",
    New_User:"New User?",
    MobileNo_notregistered:"MobileNo not registered",
    invalid_credentials:"invalid credentials",
    Logout:"Logout",
    Registration:"Registration",
    Full_Name:"Full Name",
    Email_ID:"Email ID",
    Re_Password:"Re-Password",
    OTP:"OTP",
    OTPsuccessfully_resend:"OTP successfully resend to registered mobile number",
    Sign_Up:"Sign Up",
    Submit:"Submit",
    Animal_ForSale:"Animal for sale",
    Animal_Age:"Animal age",
    Animal_ForSale_Details:"Animal for sale details",
    Animal_ForSale_List:"Animal for sale list",
    Price:"Price",
    Currency:"Currency",
    Ex_Rate:"Ex.Rate",
    Local_Price:"Local price",
    Standard_PriceDetails:"Standard price details",
    Price_List:"Price list",
    Buyer_Name:"Buyer name",
    Buyer_Address:"Buyer address",
    Buyer_PhoneNo:"Buyer phone number",
    Buyer_MobileNo:"Buyer mobile number",
    Discount:"Discount",
    Total_Price:"Total price",
    Animal_SaleEntryDetails:"Animal Sale Entry Details",
    Sale_EntryList:"Sale entry list",
    Animal_SaleEntryList:"Animal sale entry list",
    Chicken_ForSales:"Chicken for sales",
    Sale_Entry:"Sale Entry",
    Give_Vaccine:"Give Vaccine",
    Give_VaccineList:"Give vaccine list",
    Purchased_Vaccine:"Purchased vaccine",
    Purchased_VaccineList:"Purchased vaccine list",
    Vaccine:"Vaccine",
    Purchased_VaccineList:"Purchased vaccine list",
    Vaccine_ScheduleList:"Vaccine schedule list",
    Give_VaccineList:"Give vaccine list",
    Vaccine_Due :"Vaccine due",
    Vaccine_Type:"Vaccine type",
    Vaccine_Name:"Vaccine name",
    Vaccine_Company:"Vaccine company",
    Vaccine_Schedule:"Vaccine schedule"
  },
  en:{
    Breed_Details:"Breed details",
    Breed_Name:"Breed name",
    Breed:"Breed",
    Save:"Save",
    Reset:"Reset",
    Breed_List:"Breed list",
    Search:"Search",
    Chicken_Treatment:"Chicken treatment",
    Chicken_Treatment_List:"Chicken treatment list",
    Purchased_Medicine_List:"Purchased medicine list",
    Purchased_Medicine:"Purchased medicine",
    Animal_Code:"Animal code",
    Medicine_Name:"Medicine name",
    Medicine_Type:"Medicine type",
    Medicine_Company:"Medicine company",
    Purchase_Date:"Purchase date",
    Reason:"Reason",
    Start_Date:"Start date",
    End_Date:"End date",
    Expiry_Date:"Expiry date",
    Batch_No:"Batch number",
    Quantity:"Quantity",
    Dosage:"Dosage",
    Remarks:"Remarks",
    Saved_successfully:"Saved successfully",
    Mandatory_fields:"Please enter all mandatory fields",
    Chicken_Treatment_Detail:"Chicken treatment detail",
    Chicken_Treatment_Entry_List:"Chicken treatment entry list",
    Supplied_By:"Supplied By",
    Chicken_Profile_Details:"Chicken profile details",
    Animal_Name:"Name",
    Animal_Symbol:"Symbol",
    Animal_Status:"Animal status",
    Cause_Of_Death:"Cause of death",
    Gender:"Gender",
    Sire_Code:"Sire code",
    Date_Of_Birth:"Date of birth",
    Breeder_Code:"Breeder code",
    Breeder_Formula:"Breeder formula",
    Talents:"Talents",
    Weight:"Weight",
    Fighting_Record:"Fighting record",
    Standard_Price:"Standard price",
    Chicken_Details:"Chicken details",
    Clear_Photo:"Clear photo",
    Select_Photo:"Select photo",
    Chicken_Profile_List:"Chicken profile list",
    Main_Dashboard:"Main dashboard",
    My_Farm_Dashboard:"My farm dashboard",
    Sales:"Sales",
    Expense:"Expense",
    Profit_Loss:"Profit & Loss",
    Stock:"Stock",
    Expense_Name:"Expense name",
    Expense_Code:"Expense code",
    Expense_Type:"Expense type",
    Vendor_Name:"Vendor name",
    Vendor_Address:"Vendor address",
    Amount:"Amount",
    Expense_Entry_Details:"Expense entry details",
    Expense_Entry_List:"Expense entry list",
    Expenses:"Expenses",
    Master_Expense_List:"Master expense list",
    Expense_Entry_List:"Expense entry list",
    Master_Expense_Details:"Master expense details",
    Farm_Profile:"Farm profile",
    Farm_Name:"Farm name",
    Farm_Address:"Farm address",
    Phone_Number:"Phone number",
    Mobile_Number:"Mobile number",
    Social_Page:"Social page",
    Website:"Website",
    About_Us:"About us",
    Line_ID:"Line ID",
    Add_Farm_Profile:"Add farm profile",
    Clear_Logo:"Clear logo",
    Select_Logo:"Select logo",
    OTP_Sent:"OTP successfully send to registered mobile number",
    Mobile_NumberNotExists:"Mobile number is not exists",
    Forgot_Password:"Forgot password",
    Continue:"Continue",
    Invalid_OTPNumber:"Invalid OTP Number..Please Enter Valid OTP Number.",
    Resend_OTP:"Resend OTP",
    New_Password:"New password",
    Confirm_Password:"Confirm password",
    Password_Mismatch:"Password mismatch",
    Successfully_ChangedPassword:"Successfully changed your password",
    Submit:"Submit",
    Password:"Password",
    Login:"Login",
    New_User:"New User?",
    MobileNo_notregistered:"MobileNo not registered",
    invalid_credentials:"invalid credentials",
    Logout:"Logout",
    Registration:"Registration",
    Full_Name:"Full Name",
    Email_ID:"Email ID",
    Re_Password:"Re-Password",
    OTP:"OTP",
    OTPsuccessfully_resend:"OTP successfully resend to registered mobile number",
    Sign_Up:"Sign Up",
    Submit:"Submit",
    Animal_ForSale:"Animal for sale",
    Animal_Age:"Animal age",
    Animal_ForSale_Details:"Animal for sale details",
    Animal_ForSale_List:"Animal for sale list",
    Price:"Price",
    Currency:"Currency",
    Ex_Rate:"Ex.Rate",
    Local_Price:"Local price",
    Standard_PriceDetails:"Standard price details",
    Price_List:"Price list",
    Buyer_Name:"Buyer name",
    Buyer_Address:"Buyer address",
    Buyer_PhoneNo:"Buyer phone number",
    Buyer_MobileNo:"Buyer mobile number",
    Discount:"Discount",
    Total_Price:"Total price",
    Animal_SaleEntryDetails:"Animal Sale Entry Details",
    Sale_EntryList:"Sale entry list",
    Animal_SaleEntryList:"Animal sale entry list",
    Chicken_ForSales:"Chicken for sales",
    Sale_Entry:"Sale Entry",
    Give_Vaccine:"Give Vaccine",
    Give_VaccineList:"Give vaccine list",
    Purchased_Vaccine:"Purchased vaccine",
    Purchased_VaccineList:"Purchased vaccine list",
    Vaccine:"Vaccine",
    Purchased_VaccineList:"Purchased vaccine list",
    Vaccine_ScheduleList:"Vaccine schedule list",
    Give_VaccineList:"Give vaccine list",
    Vaccine_Due :"Vaccine due",
    Vaccine_Type:"Vaccine type",
    Vaccine_Name:"Vaccine name",
    Vaccine_Company:"Vaccine company",
    Vaccine_Schedule:"Vaccine schedule"
  },
  th: {
    Breed_Details:"รายละเอียดพันธุ์",
    Breed_Name:"ชื่อพันธุ์",
    Breed:"สายพันธุ์",
    Save:"บันทึก",
    Reset:"รีเซ็ต",
    Breed_List:"รายการพันธุ์",
    Search:"ค้นหา",
    Chicken_Treatment:"การรักษาด้วยไก่",
    Chicken_Treatment_List:"รายการการรักษาไก่",
    Purchased_Medicine_List:"รายการยาที่ซื้อ",
    Purchased_Medicine:"ซื้อยา",
    Animal_Code:"รหัสสัตว์",
    Medicine_Name:"ชื่อยา",
    Medicine_Type:"ประเภทยา",
    Medicine_Company:"บริษัท ยา",
    Purchase_Date:"วันที่ซื้อ",
    Reason:"เหตุผล",
    Start_Date:"วันที่เริ่มต้น",
    End_Date:"วันที่สิ้นสุด",
    Expiry_Date:"วันหมดอายุ",
    Batch_No:"หมายเลขแบทช์",
    Quantity:"ปริมาณ",
    Dosage:"ปริมาณ",
    Remarks:"หมายเหตุ",
    Saved_successfully:"บันทึกเรียบร้อยแล้ว",
    Mandatory_fields:"โปรดป้อนข้อมูลที่จำเป็นทั้งหมด",
    Chicken_Treatment_Detail:"รายละเอียดการรักษาไก่",
    Chicken_Treatment_Entry_List:"รายการรายการการรักษาไก่",
    Supplied_By:"จัดส่งโดย",
    Chicken_Profile_Details:"รายละเอียดโปรไฟล์ไก่",
    Animal_Name:"ชื่อ",
    Animal_Symbol:"สัญลักษณ์",
    Animal_Status:"สถานะสัตว์",
    Cause_Of_Death:"สาเหตุแห่งความตาย",
    Gender:"เพศ",
    Sire_Code:"รหัส Sire",
    Date_Of_Birth:"วันเกิด",
    Breeder_Code:"รหัสผู้เพาะพันธุ์",
    Breeder_Formula:"สูตรพ่อแม่พันธุ์",
    Talents:"ความสามารถพิเศษ",
    Weight:"น้ำหนัก",
    Fighting_Record:"บันทึกการต่อสู้",
    Standard_Price:"ราคามาตรฐาน",
    Chicken_Details:"รายละเอียดไก่",
    Clear_Photo:"ล้างภาพ",
    Select_Photo:"เลือกรูปภาพ",
    Chicken_Profile_List:"รายชื่อโปรไฟล์ไก่",
    Main_Dashboard:"แดชบอร์ดหลัก",
    My_Farm_Dashboard:"แดชบอร์ดฟาร์มของฉัน",
    Sales:"ขาย",
    Expense:"ค่าใช้จ่าย",
    Profit_Loss:"กำไรและขาดทุน",
    Stock:"หุ้น",
    Expense_Name:"ชื่อค่าใช้จ่าย",
    Expense_Code:"รหัสค่าใช้จ่าย",
    Expense_Type:"ประเภทค่าใช้จ่าย",
    Vendor_Name:"ชื่อผู้ขาย",
    Vendor_Address:"ที่อยู่ผู้ขาย",
    Amount:"จำนวน",
    Expense_Entry_Details:"รายละเอียดของรายการค่าใช้จ่าย",
    Expense_Entry_List:"รายการค่าใช้จ่าย",
    Expenses:"รายจ่าย",
    Master_Expense_List:"รายการค่าใช้จ่ายหลัก",
    Expense_Entry_List:"รายการค่าใช้จ่าย",
    Master_Expense_Details:"รายละเอียดค่าใช้จ่ายหลัก",
    Farm_Profile:"รายละเอียดฟาร์ม",
    Farm_Name:"ชื่อฟาร์ม",
    Farm_Address:"ที่อยู่ฟาร์ม",
    Phone_Number:"หมายเลขโทรศัพท์",
    Mobile_Number:"เบอร์มือถือ",
    Social_Page:"หน้าสังคม",
    Website:"เว็บไซต์",
    About_Us:"เกี่ยวกับเรา",
    Line_ID:"รหัสบรรทัด",
    Add_Farm_Profile:"เพิ่มโปรไฟล์ฟาร์ม",
    Clear_Logo:"ล้างโลโก้",
    Select_Logo:"เลือกโลโก้",
    OTP_Sent:"OTP ส่งลงทะเบียนหมายเลขโทรศัพท์มือถือเรียบร้อยแล้ว",
    Mobile_NumberNotExists:"หมายเลขโทรศัพท์มือถือไม่มีอยู่",
    Continue:"ต่อ",
    Invalid_OTPNumber:"หมายเลข OTP ไม่ถูกต้อง .. โปรดป้อนหมายเลข OTP ที่ถูกต้อง.",
    Resend_OTP:"ส่ง OTP ใหม่",
    New_Password:"รหัสผ่านใหม่",
    Confirm_Password:"ยืนยันรหัสผ่าน",
    Password_Mismatch:"รหัสไม่ตรงกัน",
    Successfully_ChangedPassword:"เปลี่ยนรหัสผ่านเรียบร้อยแล้ว",
    Submit:"เสนอ",
    Password:"รหัสผ่าน",
    Login:"เข้าสู่ระบบ",
    New_User:"ผู้ใช้ใหม่?",
    Forgot_Password:"ลืมรหัสผ่าน?",
    MobileNo_notregistered:"หมายเลขโทรศัพท์มือถือไม่ได้ลงทะเบียน",
    invalid_credentials:"ข้อมูลประจำตัวที่ไม่ถูกต้อง",
    Logout:"ออกจากระบบ",
    Registration:"การลงทะเบียน",
    Full_Name:"ชื่อเต็ม",
    Email_ID:"ชื่ออีเมล์",
    Re_Password:"ป้อนรหัสยืนยัน",
    OTP:"OTP",
    OTPsuccessfully_resend:"OTP ส่งถึงหมายเลขโทรศัพท์มือถือที่ลงทะเบียนแล้ว",
    Sign_Up:"ลงชื่อ",
    Submit:"เสนอ",
    Animal_ForSale:"สัตว์สำหรับขาย",
    Animal_Age:"อายุสัตว์",
    Animal_ForSale_Details:"สัตว์เพื่อขายรายละเอียด",
    Animal_ForSale_List:"สัตว์สำหรับขายรายการ",
    Price:"ราคา",
    Currency:"เงินตรา",
    Ex_Rate:"อัตราแลกเปลี่ยน",
    Local_Price:"ราคาท้องถิ่น",
    Standard_PriceDetails:"รายละเอียดราคามาตรฐาน",
    Price_List:"รายการราคา",
    Buyer_Name:"ชื่อผู้ซื้อ",
    Buyer_Address:"ที่อยู่ของผู้ซื้อ",
    Buyer_PhoneNo:"หมายเลขโทรศัพท์ของผู้ซื้อ",
    Buyer_MobileNo:"หมายเลขโทรศัพท์มือถือของผู้ซื้อ",
    Discount:"ส่วนลด",
    Total_Price:"ราคารวม",
    Animal_SaleEntryDetails:"รายละเอียดการขายสัตว์",
    Sale_EntryList:"รายการการขาย",
    Animal_SaleEntryList:"รายชื่อการขายสัตว์",
    Chicken_ForSales:"ไก่ขาย",
    Sale_Entry:"รายการขาย",
    Give_Vaccine:"ให้วัคซีน",
    Give_VaccineList:"ให้รายชื่อวัคซีน",
    Purchased_Vaccine:"ซื้อวัคซีนแล้ว",
    Purchased_VaccineList:"ซื้อรายชื่อวัคซีน",
    Vaccine:"วัคซีน",
    Purchased_VaccineList:"ซื้อรายชื่อวัคซีน",
    Vaccine_ScheduleList:"รายการตารางวัคซีน",
    Give_VaccineList:"ให้รายชื่อวัคซีน",
    Vaccine_Due :"วัคซีนที่ครบกำหนด",
    Vaccine_Type:"วัคซีนชนิด",
    Vaccine_Name:"ชื่อวัคซีน",
    Vaccine_Company:"บริษัท วัคซีน",
    Vaccine_Schedule:"กำหนดการวัคซีน"
  },
  hi:{
    Breed_Details: "नस्ल विवरण", 
    Breed_Name: "नस्ल का नाम", 
    Breed: "नस्ल", 
    Save: "सहेजें", 
    Reset: "रीसेट", 
    Breed_List: "नस्ल सूची", 
    Search: "खोज", 
    Chicken_Treatment: "चिकन उपचार", 
    Chicken_Treatment_List: "चिकन उपचार सूची", 
    Purchased_Medicine_List: "खरीदी गई दवा सूची", 
    Purchased_Medicine: "खरीदी दवा", 
    Animal_Code: "पशु कोड", 
    Medicine_Name: "दवा का नाम", 
    Medicine_Type: "चिकित्सा प्रकार", 
    Medicine_Company: "दवा कंपनी", 
    Purchase_Date: "खरीद की तारीख", 
    Reason: "कारण", 
    Start_Date: "प्रारंभ दिनांक", 
    End_Date: "समाप्ति दिनांक", 
    Expiry_Date: "समाप्ति दिनांक", 
    Batch_No: "बैच संख्या", 
    Quantity: "मात्रा", 
    Dosage: "खुराक", 
    Remarks: "टिप्पणी", 
    Saved_successfully: "सफलतापूर्वक सहेजा गया", 
    Mandatory_fields: "कृपया सभी अनिवार्य फ़ील्ड दर्ज करें", 
    Chicken_Treatment_Detail: "चिकन उपचार विस्तार", 
    Chicken_Treatment_Entry_List: "चिकन उपचार प्रवेश सूची", 
    Supplied_By: "से आपूर्ति", 
    Chicken_Profile_Details: "चिकन प्रोफाइल विवरण", 
    Animal_Name: "नाम", 
    Animal_Symbol: "प्रतीक", 
    Animal_Status: "पशु स्थिति", 
    Cause_Of_Death: "मौत का कारण", 
    Gender: "लिंग", 
    Sire_Code: "श्रीमान कोड", 
    Date_Of_Birth: "जंम तिथि", 
    Breeder_Code: "ब्रीडर कोड", 
    Breeder_Formula: "ब्रीडर फार्मूला", 
    Talents: "प्रतिभा", 
    Weight: "वजन", 
    Fighting_Record: "लड़ रिकॉर्ड", 
    Standard_Price: "मानक मूल्य", 
    Chicken_Details: "चिकन विवरण", 
    Clear_Photo: "साफ़ फोटो", 
    Select_Photo: "फ़ोटो चुनें", 
    Chicken_Profile_List: "चिकन प्रोफाइल सूची", 
    Main_Dashboard: "मुख्य डैशबोर्ड", 
    My_Farm_Dashboard: "मेरा फ़ार्म डैशबोर्ड", 
    Sales: "बिक्री", 
    Expense: "व्यय", 
    Profit_Loss: "लाभ और हानि", 
    Stock: "स्टॉक", 
    Expense_Name: "व्यय का नाम", 
    Expense_Code: "व्यय कोड", 
    Expense_Type: "व्यय प्रकार", 
    Vendor_Name: "विक्रेता का नाम", 
    Vendor_Address: "विक्रेता पता", 
    Amount: "राशि", 
    Expense_Entry_Details: "व्यय प्रविष्टि विवरण", 
    Expense_Entry_List: "व्यय प्रविष्टि सूची", 
    Expenses: "खच", 
    Master_Expense_List: "मास्टर व्यय सूची", 
    Expense_Entry_List: "व्यय प्रविष्टि सूची", 
    Master_Expense_Details: "मास्टर व्यय विवरण", 
    Master_Expense_List: "मास्टर व्यय सूची", 
    Farm_Profile: "फार्म प्रोफाइल", 
    Farm_Name: "फार्म का नाम", 
    Farm_Address: "फ़ार्म पता", 
    Phone_Number: "फ़ोन नंबर", 
    Mobile_Number: "मोबाईल नंबर", 
    Social_Page: "सामाजिक पेज", 
    Website: "वेबसाइट", 
    About_Us: "हमारे बारे में", 
    Line_ID: "लाइन आईडी", 
    Add_Farm_Profile: "खेत प्रोफ़ाइल जोड़ें", 
    Clear_Logo: "स्पष्ट लोगो", 
    Select_Logo: "लोगो का चयन करें", 
    OTP_Sent: "ओटीपी सफलतापूर्वक पंजीकृत मोबाइल नंबर पर भेजें", 
    Mobile_NumberNotExists: "मोबाइल नंबर मौजूद नहीं है", 
    Forgot_Password: "पासवर्ड भूल गया", 
    Continue: "जारी रखें", 
    Invalid_OTPNumber: "अवैध ओटीपी नंबर.. कृपया मान्य ओटीपी नंबर दर्ज करें.", 
    Resend_OTP: "ओटीपी पुनः भेजें", 
    New_Password: "नया पासवर्ड", 
    Confirm_Password: "पासवर्ड की पुष्टि करें", 
    Password_Mismatch: "पासवर्ड बेमेल", 
    Successfully_ChangedPassword: "सफलतापूर्वक अपना पासवर्ड परिवर्तित", 
    Submit: "सबमिट करें", 
    Password: "पासवर्ड", 
    Login: "लॉगिन", 
    New_User: "नया उपयोगकर्ता?", 
    Forgot_Password: "पासवर्ड भूल गए?", 
    MobileNo_notregistered: "MobileNo पंजीकृत नहीं", 
    invalid_credentials: "अमान्य क्रेडेंशियल्स", 
    Logout: "लॉगआउट", 
    Registration: "पंजीकरण", 
    Full_Name: "पूरा नाम", 
    Email_ID: "ईमेल आईडी", 
    Re_Password: "फिर से पासवर्ड", 
    OTP: "ओटीपी", 
    OTPsuccessfully_resend: "ओटीपी सफलतापूर्वक पंजीकृत मोबाइल नंबर पर पुनः भेजें", 
    Sign_Up: "साइन अप करें", 
    Submit: "सबमिट करें", 
    Animal_ForSale: "बिक्री के लिए पशु", 
    Animal_Age: "पशु आयु", 
    Animal_ForSale_Details: "बिक्री विवरण के लिए पशु", 
    Animal_ForSale_List: "बिक्री की सूची के लिए पशु",
    Price: "मूल्य", 
    Currency: "मुद्रा", 
    Ex_Rate: "उदा. दर", 
    Local_Price: "स्थानीय मूल्य", 
    Standard_PriceDetails: "मानक मूल्य विवरण", 
    Price_List: "मूल्य सूची", 
    Buyer_Name: "क्रेता का नाम", 
    Buyer_Address: "खरीदार पता", 
    Buyer_PhoneNo: "क्रेता फोन नंबर", 
    Buyer_MobileNo: "क्रेता मोबाइल नंबर", 
    Discount: "डिस्काउंट", 
    Total_Price: "कुल मूल्य", 
    Animal_SaleEntryDetails: "पशु बिक्री प्रवेश विवरण", 
    Sale_EntryList: "बिक्री प्रविष्टि सूची", 
    Animal_SaleEntryList: "पशु बिक्री प्रवेश सूची", 
    Chicken_ForSales: "बिक्री के लिए चिकन", 
    Sale_Entry: "बिक्री प्रविष्टि", 
    Give_Vaccine: "टीका दे", 
    Give_VaccineList: "टीका सूची दे", 
    Purchased_Vaccine: "खरीदा वैक्सीन", 
    Purchased_VaccineList: "खरीदा वैक्सीन सूची", 
    Vaccine: "वैक्सीन", 
    Purchased_VaccineList: "खरीदा वैक्सीन सूची", 
    Vaccine_ScheduleList: "वैक्सीन अनुसूची सूची", 
    Give_VaccineList: "टीका सूची दे", 
    Vaccine_Due: "वैक्सीन के कारण", 
    Vaccine_Type: "वैक्सीन प्रकार", 
    Vaccine_Name: "वैक्सीन का नाम", 
    Vaccine_Company: "वैक्सीन कंपनी", 
    Vaccine_Schedule: "वैक्सीन अनुसूची"
  }
});